= {ProductName}

:toc: left
:icons: font
:source-highlighter: highlightjs

Welcome to the {ProductName} documentation!

== Why use {ProductName}?

You can use {ProductName} to enable continuous integration and continuous development (CI/CD) for your applications in a matter of minutes. You can also use {ProductName} to secure your software supply chain by reaching SLSA level 3 standards. And you can customize how {ProductName} builds, tests, and deploys containerized applications.  

{ProductName} is the “upstream” project for Red Hat Trusted Application Pipeline, which is an enterprise-ready version of {ProductName}. Both projects are in their early days, so their differences are currently negligible.

== These documents

You can use these documents for two basic purposes:

. Learn how to use {ProductName} in your command line interface (CLI).

. Find additional information about using {ProductName} in its web user interface (UI).

In the navigation bar of this website, you can select your preferred access method (CLI or web UI), then search for the document you need based on what stage of development you have reached. 

You can also find the glossary, which explains how certain terms are used in the context of {ProductName}, and visit pages about contributing to this documentation and getting support for {ProductName}.