# Copyright 2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0s

name: Publish preview

on:
  workflow_run:
    workflows: "Check pull request"
    types:
      - completed

jobs:
  publish:
    name: Publish preview on netlify
    runs-on: ubuntu-22.04
    steps:
      - name: Download doc-content artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: website
          path: content
          
      - name: Unzip website artifact
        run: unzip -q website.zip
        
      - name: Set PR_NUMBER and PR_SHA variables
        id: vars
        run: |
          echo "pr_number=$(<content/PR_NUMBER)" >> $GITHUB_OUTPUT
          echo "pr_sha=$(<content/PR_SHA)" >> $GITHUB_OUTPUT
      - name: Publish preview netlify
        uses: netlify/actions/cli@master
        id: netlify-publish
        with:
          args: deploy --dir=content/public --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Update status comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎊 Navigate the preview: ${{ steps.netlify-publish.outputs.NETLIFY_URL }} 🎊
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.vars.outputs.pr_number }}
